# Generated by Django 4.2.3 on 2023-08-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='demo', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
